config/routes.rb
Rails.application.routes.draw do
  resources :stock_controls
  resources :impressoras
  resources :vpns
  # Define a rota root para o index da home
  root 'home#index'

  # Configura as rotas do Devise para autenticação de usuários
  devise_for :users

  # Define todas as rotas RESTful para artigos (index, show, new, create, edit, update, destroy)
  resources :articles
  resources :stock_controls

  # Rota explícita para o index da home, com alias 'home_index'
  get 'home/index', as: 'home_index'

  # Outras rotas e configurações adicionais...
end
  # ... outras rotas e configurações adicionais ...
  # rails server -b 10.0.60.189
  #kill -9 3173

app/models/impressora.rb
class Impressora < ApplicationRecord
  has_one_attached :foto
  has_one_attached :toner_foto
  validates :toner_quantity, numericality: { greater_than_or_equal_to: 0 }
  validates :stock, numericality: { greater_than_or_equal_to: 0 }
end

app/controllers/impressoras_controller.rb
class ImpressorasController < ApplicationController
  before_action :set_impressora, only: %i[ show edit update destroy ]

  # GET /impressoras or /impressoras.json
  def index
    @impressoras = Impressora.all
  end

  # GET /impressoras/1 or /impressoras/1.json
  def show
  end

  # GET /impressoras/new
  def new
    @impressora = Impressora.new
  end

  # GET /impressoras/1/edit
  def edit
  end

  # POST /impressoras or /impressoras.json
  def create
    @impressora = Impressora.new(impressora_params)

    respond_to do |format|
      if @impressora.save
        format.html { redirect_to impressora_url(@impressora), notice: "Impressora was successfully created." }
        format.json { render :show, status: :created, location: @impressora }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @impressora.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /impressoras/1 or /impressoras/1.json
  def update
    respond_to do |format|
      if @impressora.update(impressora_params)
        format.html { redirect_to impressora_url(@impressora), notice: "Impressora was successfully updated." }
        format.json { render :show, status: :ok, location: @impressora }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @impressora.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /impressoras/1 or /impressoras/1.json
  def destroy
    @impressora.destroy!

    respond_to do |format|
      format.html { redirect_to impressoras_url, notice: "Impressora was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_impressora
      @impressora = Impressora.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def impressora_params
      params.require(:impressora).permit(
        :departamento, :loja, :proprietario, :modelo, :nPatrimonio, :nSerie, :nGps,
        :foto, :toner_foto, :tonerModelo, :toner_quantity, :stock, :ativa, :tempodeuso,
        :info, :info1, :info3, :info4, :info5
      )
    end
end

app/helpers/impressoras_helper.rb
module ImpressorasHelper
end

app/views/impressoras/_form.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= content_for?(:title) ? yield(:title) : 'Meu Aplicativo' %></title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <!-- Incluir a biblioteca jQuery -->
  <%= javascript_include_tag 'https://code.jquery.com/jquery-3.6.0.min.js' %>

  <!-- Incluir a biblioteca do Google Charts -->
  <%= javascript_include_tag '//www.gstatic.com/charts/loader.js' %>

  <!-- Carregar o arquivo JavaScript principal -->
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  <!-- Incluir o CSS do Bootstrap -->
  <%= stylesheet_link_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css', media: 'all', 'data-turbolinks-track': 'reload' %>

  <!-- Carregar o arquivo de estilo específico -->
  <%= stylesheet_link_tag 'impressoras/impressoras', media: 'all', 'data-turbolinks-track': 'reload' %>

  <!-- Incluir a referência à folha de estilo específica da view -->
  <%= yield :stylesheet %>
</head>
<body>

  <div class="container mt-4">
    <div class="card shadow-lg">
      <div class="card-header text-center bg-primary text-white">
        <h3><%= content_for?(:title) ? yield(:title) : 'Impressoras' %></h3>
      </div>
      <div class="card-body">
        <% if @impressora.errors.any? %>
          <div class="alert alert-danger">
            <h2><%= pluralize(@impressora.errors.count, "erro") %> impedem esta impressora de ser salva:</h2>
            <ul>
              <% @impressora.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>

        <%= form_with(model: @impressora, local: true, html: { multipart: true }) do |form| %>
          <div class="form-group">
            <%= form.label :departamento %>
            <%= form.text_field :departamento, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= form.label :loja %>
            <%= form.text_field :loja, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= form.label :proprietario %>
            <%= form.text_field :proprietario, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= form.label :modelo %>
            <%= form.text_field :modelo, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= form.label :nPatrimonio %>
            <%= form.text_field :nPatrimonio, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= form.label :nSerie %>
            <%= form.text_field :nSerie, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= form.label :nGps %>
            <%= form.text_field :nGps, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= form.label :foto, "Foto da Impressora" %>
            <%= form.file_field :foto, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= form.label :toner_foto, "Foto do Toner" %>
            <%= form.file_field :toner_foto, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= form.label :tonerModelo %>
            <%= form.text_field :tonerModelo, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= form.label :toner_quantity, "Quantidade de Toner" %>
            <%= form.number_field :toner_quantity, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= form.label :stock, "Estoque" %>
            <%= form.number_field :stock, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= form.label :ativa %>
            <%= form.check_box :ativa %>
          </div>

          <div class="form-group">
            <%= form.label :tempodeuso %>
            <%= form.number_field :tempodeuso, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= form.label :info %>
            <%= form.text_area :info, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= form.label :info1 %>
            <%= form.text_area :info1, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= form.label :info3 %>
            <%= form.text_area :info3, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= form.label :info4 %>
            <%= form.text_area :info4, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= form.label :info5 %>
            <%= form.text_area :info5, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= form.submit class: 'btn btn-primary' %>
          </div>
        <% end %>
      </div>
    </div>
  </div>

  <!-- Inclusão do JavaScript do Bootstrap -->
  <%= javascript_include_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js', 'data-turbolinks-track': 'reload' %>

  <%= javascript_tag do %>
    // Carregar a biblioteca do Google Charts
    google.charts.load('current', { 'packages': ['corechart'] });
  <% end %>

</body>
</html>

app/views/impressoras/_impressora.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= content_for?(:title) ? yield(:title) : 'Meu Aplicativo' %></title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <!-- Incluir a biblioteca jQuery -->
  <%= javascript_include_tag 'https://code.jquery.com/jquery-3.6.0.min.js' %>

  <!-- Incluir a biblioteca do Google Charts -->
  <%= javascript_include_tag '//www.gstatic.com/charts/loader.js' %>

  <!-- Carregar o arquivo JavaScript principal -->
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  <!-- Incluir o CSS do Bootstrap -->
  <%= stylesheet_link_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css', media: 'all', 'data-turbolinks-track': 'reload' %>

  <!-- Carregar o arquivo de estilo específico -->
  <%= stylesheet_link_tag 'home/home', media: 'all', 'data-turbolinks-track': 'reload' %>

  <!-- Incluir a referência à folha de estilo específica da view -->
  <%= yield :stylesheet %>
</head>
<body>

  <div class="container mt-4">
    <div id="<%= dom_id impressora %>" class="card">
      <div class="card-body">
        <h5 class="card-title"><%= impressora.modelo %> (Modelo)</h5>

        <p class="card-text">
          <strong>Departamento:</strong> <%= impressora.departamento %><br>
          <strong>Loja:</strong> <%= impressora.loja %><br>
          <strong>Proprietário:</strong> <%= impressora.proprietario %><br>
          <strong>Modelo:</strong> <%= impressora.modelo %><br>
          <strong>Nº Patrimônio:</strong> <%= impressora.nPatrimonio %><br>
          <strong>Nº Série:</strong> <%= impressora.nSerie %><br>
          <strong>Nº GPS:</strong> <%= impressora.nGps %><br>
          <strong>Modelo do Toner:</strong> <%= impressora.tonerModelo %><br>
          <strong>Ativa:</strong> <%= impressora.ativa ? 'Sim' : 'Não' %><br>
          <strong>Tempo de Uso:</strong> <%= impressora.tempodeuso %> horas<br>
          <strong>Info:</strong> <%= impressora.info %><br>
          <strong>Info1:</strong> <%= impressora.info1 %><br>
          <strong>Info3:</strong> <%= impressora.info3 %><br>
          <strong>Info4:</strong> <%= impressora.info4 %><br>
          <strong>Info5:</strong> <%= impressora.info5 %>
        </p>

        <div class="mt-3">
          <%= link_to "Edit this impressora", edit_impressora_path(impressora), class: "btn btn-primary" %>
          <%= button_to "Destroy this impressora", impressora, method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger" %>
          <%= link_to "Back to impressoras", impressoras_path, class: "btn btn-secondary" %>
        </div>
      </div>
    </div>
  </div>

  <!-- Inclusão do JavaScript do Bootstrap -->
  <%= javascript_include_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js', 'data-turbolinks-track': 'reload' %>

  <%= javascript_tag do %>
    // Carregar a biblioteca do Google Charts
    google.charts.load('current', { 'packages': ['corechart'] });
  <% end %>

</body>
</html>

app/views/impressoras/edit.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= content_for?(:title) ? yield(:title) : 'Meu Aplicativo' %></title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <!-- Incluir a biblioteca jQuery -->
  <%= javascript_include_tag 'https://code.jquery.com/jquery-3.6.0.min.js' %>

  <!-- Incluir a biblioteca do Google Charts -->
  <%= javascript_include_tag '//www.gstatic.com/charts/loader.js' %>

  <!-- Carregar o arquivo JavaScript principal -->
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  <!-- Incluir o CSS do Bootstrap -->
  <%= stylesheet_link_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css', media: 'all', 'data-turbolinks-track': 'reload' %>

  <!-- Carregar o arquivo de estilo específico -->
  <%= stylesheet_link_tag 'home/home', media: 'all', 'data-turbolinks-track': 'reload' %>

  <!-- Incluir a referência à folha de estilo específica da view -->
  <%= yield :stylesheet %>
</head>
<body>

  <div class="container mt-4">
    <h1><%= content_for?(:title) ? yield(:title) : 'Editing Impressora' %></h1>

    <%= render "form", impressora: @impressora %>

    <div class="mt-3">
      <%= link_to "Show this impressora", @impressora, class: "btn btn-info" %>
      <%= link_to "Back to impressoras", impressoras_path, class: "btn btn-secondary" %>
    </div>
  </div>

  <!-- Inclusão do JavaScript do Bootstrap -->
  <%= javascript_include_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js', 'data-turbolinks-track': 'reload' %>

  <%= javascript_tag do %>
    // Carregar a biblioteca do Google Charts
    google.charts.load('current', { 'packages': ['corechart'] });
  <% end %>

</body>
</html>

app/views/impressoras/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= content_for?(:title) ? yield(:title) : 'Meu Aplicativo' %></title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <!-- Incluir o CSS do Bootstrap -->
  <%= stylesheet_link_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css', media: 'all', 'data-turbolinks-track': 'reload' %>

  <!-- Carregar o arquivo de estilo específico -->
  <%= stylesheet_link_tag 'home/home', media: 'all', 'data-turbolinks-track': 'reload' %>

  <!-- Incluir o jQuery -->
  <%= javascript_include_tag 'https://code.jquery.com/jquery-3.6.0.min.js' %>

  <!-- Incluir o JavaScript do Bootstrap -->
  <%= javascript_include_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js' %>

  <!-- Carregar o arquivo JavaScript principal -->
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  <!-- Incluir a referência à folha de estilo específica da view -->
  <%= yield :stylesheet %>

  <!-- Carregar a biblioteca do Google Charts -->
  <%= javascript_tag do %>
    google.charts.load('current', { 'packages': ['corechart'] });
  <% end %>
</head>
<body>
  <div class="container mt-4">
    <h1><%= content_for?(:title) ? yield(:title) : 'Impressoras' %></h1>

    <% if notice.present? %>
      <div class="alert alert-success">
        <%= notice %>
      </div>
    <% end %>

    <!-- Formulário de Pesquisa -->
    <%= form_with(url: impressoras_path, method: :get, local: true, class: 'mb-4') do %>
      <div class="form-group">
        <%= label_tag :search, "Pesquisar Impressoras", class: 'form-label' %>
        <%= text_field_tag :search, params[:search], class: 'form-control', placeholder: 'Digite o modelo da impressora' %>
        <div class="mt-2">
        <%= submit_tag 'Pesquisar', class: 'btn btn-primary' %>
                  <%= link_to 'Nova Impressora', new_impressora_path, class: 'btn btn-primary' %>

        </div>
      </div>
    <% end %>

        <!-- Lista de impressoras -->
    <div class="list-group">
      <% @impressoras.each do |impressora| %>
        <div class="list-group-item list-group-item-action mb-3">
          <div class="d-flex w-100 justify-content-between">
  <strong>Departamento:</strong> <%= impressora.departamento %><br>
  <strong>Criado em:</strong> <%= impressora.created_at.strftime("%d/%m/%Y") if impressora.created_at.present? %>
          </div>
          <p class="mb-1"><%= truncate(impressora.modelo, length: 150) %></p>

          <%= link_to 'Ver Detalhes', impressora_path(impressora), class: 'btn btn-info btn-sm' %>
        </div>
      <% end %>
    </div>
  </div>
  </div>
</body>
</html>

app/views/impressoras/new.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= content_for?(:title) ? yield(:title) : 'Meu Aplicativo' %></title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <!-- Incluir a biblioteca jQuery -->
  <%= javascript_include_tag 'https://code.jquery.com/jquery-3.6.0.min.js' %>

  <!-- Incluir a biblioteca do Google Charts -->
  <%= javascript_include_tag '//www.gstatic.com/charts/loader.js' %>

  <!-- Carregar o arquivo JavaScript principal -->
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  <!-- Incluir o CSS do Bootstrap -->
  <%= stylesheet_link_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css', media: 'all', 'data-turbolinks-track': 'reload' %>

  <!-- Carregar o arquivo de estilo específico -->
  <%= stylesheet_link_tag 'impressoras/impressoras', media: 'all', 'data-turbolinks-track': 'reload' %>

  <!-- Incluir a referência à folha de estilo específica da view -->
  <%= yield :stylesheet %>
</head>
<body>

  <div class="container mt-4">

    <%= render "form", impressora: @impressora %>

    <br>

    <div>
      <%= link_to "Back to impressoras", impressoras_path, class: "btn btn-secondary" %>
    </div>
  </div>


  <%= javascript_tag do %>
    // Carregar a biblioteca do Google Charts
    google.charts.load('current', { 'packages': ['corechart'] });
  <% end %>

</body>
</html>

app/views/impressoras/show.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= content_for?(:title) ? yield(:title) : 'Meu Aplicativo' %></title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <!-- Incluir a biblioteca jQuery -->
  <%= javascript_include_tag 'https://code.jquery.com/jquery-3.6.0.min.js' %>

  <!-- Incluir a biblioteca do Google Charts -->
  <%= javascript_include_tag '//www.gstatic.com/charts/loader.js' %>

  <!-- Carregar o arquivo JavaScript principal -->
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  <!-- Incluir o CSS do Bootstrap -->
  <%= stylesheet_link_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css', media: 'all', 'data-turbolinks-track': 'reload' %>

  <!-- Incluir a referência à folha de estilo específica da view -->
  <%= yield :stylesheet %>
</head>
<body>


    <div class="row">
      <div class="col-lg-8 col-md-12">
        <div class="card border-primary mb-4">
          <div class="card-header bg-primary text-white">
            <h4 class="mb-0"><%= @impressora.modelo %></h4>
          </div>
          <div class="card-body">
            <h5 class="card-title">Detalhes da Impressora</h5>
            <p class="card-text">
              <strong>Modelo:</strong> <%= @impressora.modelo %><br>
              <strong>Proprietário:</strong> <%= @impressora.proprietario %><br>
              <strong>Local:</strong> <%= @impressora.departamento %>
            </p>

            <div class="row">
              <div class="col-md-6 mb-3">
                <h6>Foto da Impressora</h6>
                <% if @impressora.foto.attached? %>
                  <%= image_tag @impressora.foto, class: "img-fluid rounded" %>
                <% else %>
                  <span class="text-muted">Nenhuma foto disponível</span>
                <% end %>
              </div>
              <div class="col-md-6 mb-3">
                <h6>Foto do Toner</h6>
                <% if @impressora.toner_foto.attached? %>
                  <%= image_tag @impressora.toner_foto, class: "img-fluid rounded" %>
                <% else %>
                  <span class="text-muted">Nenhuma foto disponível</span>
                <% end %>
              </div>
            </div>

            <div class="d-flex justify-content-between">
              <%= link_to "Editar Impressora", edit_impressora_path(@impressora), class: "btn btn-warning" %>
              <%= button_to "Excluir Impressora", @impressora, method: :delete, data: { confirm: 'Tem certeza que deseja excluir?' }, class: "btn btn-danger" %>
              <%= link_to "Voltar", impressoras_path, class: "btn btn-secondary" %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <!-- Inclusão do JavaScript do Bootstrap -->
  <%= javascript_include_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js', 'data-turbolinks-track': 'reload' %>

  <%= javascript_tag do %>
    // Carregar a biblioteca do Google Charts
    google.charts.load('current', { 'packages': ['corechart'] });
  <% end %>

</body>
</html>