config/routes.rb
Rails.application.routes.draw do
  resources :stock_controls
  resources :impressoras
  resources :vpns
  # Define a rota root para o index da home
  root 'home#index'

  # Configura as rotas do Devise para autenticação de usuários
  devise_for :users

  # Define todas as rotas RESTful para artigos (index, show, new, create, edit, update, destroy)
  resources :articles
  resources :stock_controls

  # Rota explícita para o index da home, com alias 'home_index'
  get 'home/index', as: 'home_index'

  # Outras rotas e configurações adicionais...
end
  # ... outras rotas e configurações adicionais ...
  # rails server -b 10.0.60.189
  #kill -9 3173

app/models/vpn.rb
class Vpn < ApplicationRecord
end

app/controllers/vpns_controller.rb
class VpnsController < ApplicationController
  before_action :set_vpn, only: %i[ show edit update destroy ]

  # GET /vpns or /vpns.json
  def index
    @vpns = Vpn.all
  end

  # GET /vpns/1 or /vpns/1.json
  def show
  end

  # GET /vpns/new
  def new
    @vpn = Vpn.new
  end

  # GET /vpns/1/edit
  def edit
  end

  # POST /vpns or /vpns.json
  def create
    @vpn = Vpn.new(vpn_params)

    respond_to do |format|
      if @vpn.save
        format.html { redirect_to vpn_url(@vpn), notice: "Vpn was successfully created." }
        format.json { render :show, status: :created, location: @vpn }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @vpn.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vpns/1 or /vpns/1.json
  def update
    respond_to do |format|
      if @vpn.update(vpn_params)
        format.html { redirect_to vpn_url(@vpn), notice: "Vpn was successfully updated." }
        format.json { render :show, status: :ok, location: @vpn }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @vpn.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vpns/1 or /vpns/1.json
  def destroy
    @vpn.destroy!

    respond_to do |format|
      format.html { redirect_to vpns_url, notice: "Vpn was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vpn
      @vpn = Vpn.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def vpn_params
      params.require(:vpn).permit(:local, :nomedaconexao, :gatewayremoto, :chave)
    end
end

app/helpers/vpns_helper.rb
module VpnsHelper
end

app/views/vpns/_form.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Meu Aplicativo</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <!-- Incluir a biblioteca jQuery -->
  <%= javascript_include_tag 'https://code.jquery.com/jquery-3.6.0.min.js' %>

  <!-- Incluir a biblioteca do Google Charts -->
  <%= javascript_include_tag '//www.gstatic.com/charts/loader.js' %>

  <!-- Carregar o arquivo JavaScript principal -->
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  <!-- Incluir o CSS do Bootstrap -->
  <%= stylesheet_link_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css', media: 'all', 'data-turbolinks-track': 'reload' %>

  <!-- Carregar o arquivo de estilo específico -->
  <%= stylesheet_link_tag 'vpns/vpns', media: 'all', 'data-turbolinks-track': 'reload' %>

  <!-- Incluir a referência à folha de estilo específica da view -->
  <%= yield :stylesheet %>
</head>
<body>

  <div class="container mt-5">
    <div class="card shadow-lg">
      <div class="card-header text-center bg-primary text-white">
        <h3>Configurar VPN</h3>
      </div>
      <div class="card-body">
        <%= form_with(model: vpn, local: true, class: "p-3") do |form| %>
          <!-- Exibir erros de validação -->
          <% if vpn.errors.any? %>
            <div class="alert alert-danger">
              <h4><%= pluralize(vpn.errors.count, "erro") %> impedem esta VPN de ser salva:</h4>
              <ul>
                <% vpn.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                <% end %>
              </ul>
            </div>
          <% end %>

          <!-- Campo Local -->
          <div class="form-group">
            <%= form.label :local, class: "font-weight-bold" %>
            <%= form.text_field :local, class: "form-control", placeholder: "Insira o local" %>
          </div>

          <!-- Campo Nome da Conexão -->
          <div class="form-group">
            <%= form.label :nomedaconexao, class: "font-weight-bold" %>
            <%= form.text_field :nomedaconexao, class: "form-control", placeholder: "Insira o nome da conexão" %>
          </div>

          <!-- Campo Gateway Remoto -->
          <div class="form-group">
            <%= form.label :gatewayremoto, class: "font-weight-bold" %>
            <%= form.text_field :gatewayremoto, class: "form-control", placeholder: "Insira o gateway remoto" %>
          </div>

          <!-- Campo Chave -->
          <div class="form-group">
            <%= form.label :chave, class: "font-weight-bold" %>
            <%= form.text_field :chave, class: "form-control", placeholder: "Insira a chave de conexão" %>
          </div>

          <!-- Botão de submissão -->
          <div class="text-center">
            <%= form.submit 'Salvar VPN', class: 'btn btn-success btn-lg' %>
          </div>
        <% end %>
      </div>
    </div>
  </div>

  <!-- Inclusão do JavaScript do Bootstrap -->
  <%= javascript_include_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js', 'data-turbolinks-track': 'reload' %>

  <%= javascript_tag do %>
    // Carregar a biblioteca do Google Charts
    google.charts.load('current', { 'packages': ['corechart'] });
  <% end %>

</body>
</html>

app/views/vpns/_vpn.html.erb
<div id="<%= dom_id vpn %>">
  <p>
    <strong>Local:</strong>
    <%= vpn.local %>
  </p>

  <p>
    <strong>Nomedaconexao:</strong>
    <%= vpn.nomedaconexao %>
  </p>

  <p>
    <strong>Gatewayremoto:</strong>
    <%= vpn.gatewayremoto %>
  </p>

  <p>
    <strong>Chave:</strong>
    <%= vpn.chave %>
  </p>

</div>

app/views/vpns/edit.html.erb
<% content_for :title, "Editing VPN" %>



<%= render "form", vpn: @vpn %>

<br>

<div>
  <%= link_to "Show this VPN", @vpn, class: "btn btn-info" %> |
  <%= link_to "Back to VPNs", vpns_path, class: "btn btn-secondary" %>
</div>

app/views/vpns/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= content_for?(:title) ? yield(:title) : 'Meu Aplicativo' %></title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <!-- Incluir bibliotecas jQuery e Google Charts -->
  <%= javascript_include_tag 'https://code.jquery.com/jquery-3.6.0.min.js' %>
  <%= javascript_include_tag '//www.gstatic.com/charts/loader.js' %>

  <!-- Arquivo JavaScript principal -->
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  <!-- Incluir CSS do Bootstrap -->
  <%= stylesheet_link_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css', media: 'all', 'data-turbolinks-track': 'reload' %>

  <!-- Estilo específico -->
  <%= stylesheet_link_tag 'vpns/vpns', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= yield :stylesheet %>
</head>

<body>
  <div class="container mt-4">
    <% content_for :title, "VPNs" %>
    <h1><%= yield(:title) %></h1>

    <% if notice.present? %>
      <div class="alert alert-success">
        <%= notice %>
      </div>
    <% end %>


    <!-- Formulário de Pesquisa -->
    <%= form_with(url: vpns_path, method: :get, local: true, class: 'mb-4') do %>
      <div class="form-group">
        <%= label_tag :search, "Pesquisar Vpns", class: 'form-label' %>
        <%= text_field_tag :search, params[:search], class: 'form-control', placeholder: 'Digite o modelo da impressora' %>
        <div class="mt-2">
        <%= submit_tag 'Pesquisar', class: 'btn btn-primary' %>
                  <%= link_to 'Nova vpns', new_vpn_path, class: 'btn btn-primary' %>

        </div>
      </div>
    <% end %>

    <!-- Lista de VPNs -->
    <div class="list-group">
      <% @vpns.each do |vpn| %>
        <div class="list-group-item list-group-item-action mb-3">
          <div class="d-flex w-100 justify-content-between">
            <div>
              <strong>Local:</strong> <%= vpn.local %><br>
              <strong>Gateway Remoto:</strong> <%= vpn.gatewayremoto %><br>
              <strong>Chave:</strong> <%= vpn.chave %>
            </div>
            <%= link_to 'Ver Detalhes', vpn_path(vpn), class: 'btn btn-info btn-sm' %>
          </div>
        </div>
      <% end %>
    </div>


    <!-- Paginação -->
    <div class="d-flex justify-content-center mt-4">
    </div>
  </div>

  <!-- Inclusão do JavaScript do Bootstrap -->
  <%= javascript_include_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js', 'data-turbolinks-track': 'reload' %>

  <!-- Carregar Google Charts -->
  <%= javascript_tag do %>
    google.charts.load('current', { 'packages': ['corechart'] });
  <% end %>
</body>
</html>

app/views/vpns/new.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= content_for?(:title) ? yield(:title) : 'Meu Aplicativo' %></title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <!-- Incluir a biblioteca jQuery -->
  <%= javascript_include_tag 'https://code.jquery.com/jquery-3.6.0.min.js' %>

  <!-- Incluir a biblioteca do Google Charts -->
  <%= javascript_include_tag '//www.gstatic.com/charts/loader.js' %>

  <!-- Carregar o arquivo JavaScript principal -->
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  <!-- Incluir o CSS do Bootstrap -->
  <%= stylesheet_link_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css', media: 'all', 'data-turbolinks-track': 'reload' %>

  <!-- Carregar o arquivo de estilo específico -->
  <%= stylesheet_link_tag 'home/home', media: 'all', 'data-turbolinks-track': 'reload' %>

  <!-- Incluir a referência à folha de estilo específica da view -->
  <%= yield :stylesheet %>
</head>
<body>

  <div class="container mt-4">
    <h1 class="mb-4">New VPN</h1>

    <!-- Renderizar o formulário para o novo VPN -->
    <%= render "form", vpn: @vpn %>

    <br>

    <div class="mt-3">
      <%= link_to "Back to VPNs", vpns_path, class: "btn btn-secondary" %>
    </div>
  </div>

  <!-- Inclusão do JavaScript do Bootstrap -->
  <%= javascript_include_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js', 'data-turbolinks-track': 'reload' %>

  <%= javascript_tag do %>
    // Carregar a biblioteca do Google Charts
    google.charts.load('current', { 'packages': ['corechart'] });
  <% end %>

</body>
</html>

app/views/vpns/show.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Detalhes da VPN</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <!-- Incluir a biblioteca jQuery -->
  <%= javascript_include_tag 'https://code.jquery.com/jquery-3.6.0.min.js' %>

  <!-- Incluir a biblioteca do Google Charts -->
  <%= javascript_include_tag '//www.gstatic.com/charts/loader.js' %>

  <!-- Carregar o arquivo JavaScript principal -->
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  <!-- Incluir o CSS do Bootstrap -->
  <%= stylesheet_link_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css', media: 'all', 'data-turbolinks-track': 'reload' %>

  <!-- Carregar o arquivo de estilo específico -->
  <%= stylesheet_link_tag 'vpns/show', media: 'all', 'data-turbolinks-track': 'reload' %>

  <!-- Incluir a referência à folha de estilo específica da view -->
  <%= yield :stylesheet %>
</head>
<body>
  <div class="container mt-5">
    <!-- Mensagens de notificação -->
    <% if notice.present? %>
      <div class="alert alert-success alert-dismissible fade show" role="alert">
        <%= notice %>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    <% end %>

    <!-- Título da página -->
    <h1 class="text-center mb-4">Detalhes da VPN</h1>

    <!-- Detalhes da VPN em formato de tabela -->
    <div class="card shadow-sm mb-4">
      <div class="card-body">
        <div class="table-responsive">
          <table class="table table-striped table-bordered">
            <thead class="thead-dark">
              <tr>
                <th scope="col">Atributo</th>
                <th scope="col">Valor</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td><strong>Local</strong></td>
                <td><%= @vpn.local %></td>
              </tr>
              <tr>
                <td><strong>Nome da Conexão</strong></td>
                <td><%= @vpn.nomedaconexao %></td>
              </tr>
              <tr>
                <td><strong>Gateway Remoto</strong></td>
                <td><%= @vpn.gatewayremoto %></td>
              </tr>
              <tr>
                <td><strong>Chave</strong></td>
                <td><%= @vpn.chave %></td>
              </tr>
            </tbody>
          </table>
        </div>

        <!-- Botões de ação -->
        <div class="d-flex justify-content-center mt-4">
          <%= link_to 'Editar', edit_vpn_path(@vpn), class: 'btn btn-warning btn-lg mx-2' %>
          <%= button_to @vpn, method: :delete, data: { confirm: 'Tem certeza que deseja excluir esta VPN?' }, class: 'btn btn-danger btn-lg mx-2' do %>
            Excluir
          <% end %>
          <%= link_to 'Voltar', vpns_path, class: 'btn btn-secondary btn-lg mx-2' %>
        </div>
      </div>
    </div>
  </div>

  <!-- Inclusão do JavaScript do Bootstrap -->
  <%= javascript_include_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js', 'data-turbolinks-track': 'reload' %>

  <%= javascript_tag do %>
    // Carregar a biblioteca do Google Charts
    google.charts.load('current', { 'packages': ['corechart'] });
  <% end %>
</body>
</html>